# Generated by Django 3.1.2 on 2020-11-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='centerpitch.jpg', upload_to='article_pics'),
        ),
    ]
