# Generated by Django 3.1.2 on 2020-11-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='inthenet.jpg', upload_to='article_pics'),
        ),
    ]
