# Generated by Django 3.1.2 on 2020-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201117_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='inthenet.jpg', upload_to='media/article_pics'),
        ),
    ]
