# Generated by Django 3.1.2 on 2020-11-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_package_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
