# Generated by Django 3.1.2 on 2020-11-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_package_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='order_total',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='package',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
